// <auto-generated />
using System;
using EDurianstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("EDurianstore.Models.Durians", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Diskon")
                        .HasColumnType("numeric");

                    b.Property<string>("Gambar")
                        .HasColumnType("text");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric");

                    b.Property<string>("Keadaan")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.Property<DateTime>("PembelianPada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.Property<string>("Ukuran")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Durians");
                });

            modelBuilder.Entity("EDurianstore.Models.Keranjangs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Diskon")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Keranjangs");
                });

            modelBuilder.Entity("EDurianstore.Models.Penggunas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<decimal>("Dana")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Katasandi")
                        .HasColumnType("text");

                    b.Property<string>("Namapengguna")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telepon")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Penggunas");
                });

            modelBuilder.Entity("EDurianstore.Models.PesananDurians", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Diskon")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric");

                    b.Property<int>("IDDurian")
                        .HasColumnType("integer");

                    b.Property<int>("IDPesanan")
                        .HasColumnType("integer");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("PesananDurians");
                });

            modelBuilder.Entity("EDurianstore.Models.Pesanans", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<string>("NomorPesanan")
                        .HasColumnType("text");

                    b.Property<string>("StatusPesanan")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPesanan")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Pesanans");
                });
#pragma warning restore 612, 618
        }
    }
}
